#!/usr/bin/env node
const { WarmerExtension } = require('/opt/nodejs/warmer');

async function main() {
    try {
        const extension = new WarmerExtension();
        const extensionId = await extension.register();
        console.log('Lambda Warmer Extension registered:', extensionId);
        await extension.processEvents();
    } catch (error) {
        console.error('Lambda Warmer Extension error:', error);
        process.exit(1);
    }
}

main().catch(error => {
    console.error('Lambda Warmer Extension fatal error:', error);
    process.exit(1);
});
