# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
openapi.yaml:
  no-server-example.com:
    - "#/servers/1/url"
    - "#/servers/2/url"
    - "#/servers/3/url"
  path-parameters-defined:
    - "#/paths/~1assets~1{id}/post/parameters"
    - "#/paths/~1connectors/put/parameters/0/name"
    - "#/paths/~1connectors/delete/parameters/0/name"
  no-invalid-media-type-examples:
    - >-
      #/paths/~1connectors~1s3~1explorer~1{connector_id}/get/responses/200/content/application~1json/examples/truncatedResults/value/isTruncated
    - >-
      #/paths/~1pipelines~1executions~1{executionId}/get/responses/200/content/application~1json/examples/succeededExecution/value/duration
    - >-
      #/paths/~1pipelines~1executions~1{executionId}/get/responses/200/content/application~1json/examples/failedExecution/value/duration
    - >-
      #/paths/~1pipelines~1pipeline~1{pipelineId}/get/responses/200/content/application~1json/examples/videoPipeline/value/nodes/0/position
    - >-
      #/paths/~1pipelines~1pipeline~1{pipelineId}/get/responses/200/content/application~1json/examples/videoPipeline/value/nodes/1/position
    - >-
      #/paths/~1pipelines~1pipeline~1{pipelineId}/get/responses/200/content/application~1json/examples/videoPipeline/value/nodes/2/position
    - >-
      #/paths/~1pipelines~1pipeline~1{pipelineId}/get/responses/200/content/application~1json/examples/videoPipeline/value/version
    - >-
      #/paths/~1reviews/get/responses/200/content/application~1json/examples/success/value/data/1/completedAt
    - >-
      #/paths/~1reviews/get/responses/200/content/application~1json/examples/success/value/data/2/completedAt
    - >-
      #/paths/~1reviews/get/responses/200/content/application~1json/examples/success/value/data/2/feedback
    - >-
      #/paths/~1roles/get/responses/200/content/application~1json/examples/withoutPermissions/value/data/0
    - >-
      #/paths/~1roles/get/responses/200/content/application~1json/examples/withoutPermissions/value/data/1
    - >-
      #/paths/~1roles/get/responses/200/content/application~1json/examples/withoutPermissions/value/data/2
    - >-
      #/paths/~1settings~1system~1search/put/requestBody/content/application~1json/example/analyzers/2/tokenizer
    - >-
      #/paths/~1settings~1system~1search/put/requestBody/content/application~1json/example/analyzers/2/filter
    - >-
      #/paths/~1settings~1system~1search/post/responses/200/content/application~1json/examples/successWithoutReindex/value/reindexJobId
  no-unused-components:
    - "#/components/schemas/PaginationRequest"
    - "#/components/schemas/PaginatedResponse"
